name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bradennapier/eslint-plus-action@v3.4.2

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Detect changed files
        uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          files: |
            **/*.md
            **/*.mdx

      - name: Run markdownlint on changed files
        uses: DavidAnson/markdownlint-cli2-action@v22
        if: steps.changed-files.output.any_changed == 'true'
        with:
          config: '.markdownlint-cli2.jsonc'

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Detect changed files
        uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          files: |
            **/*.scss

      - name: Run stylelint on changed files
        uses: actions-hub/stylelint@master
        if: steps.changed-files.output.any_changed == 'true'
        env:
          PATTERN: "*.scss"
